"""
logic5.py — PDB Repair & Boltz-2 Structure Prediction
======================================================
Sits between Step 1 (Data Input) and the prppi call in logic.py.

Responsibilities:
  1. Inspect an incoming PDB for missing side chains and/or missing residues.
  2. Route to the appropriate repair strategy:
       • Missing side chains only  → PDBFixer (fast, in-process)
       • Missing residues/loops    → Boltz-2  (re-predicts full complex)
  3. For mutant sequences generated by the algorithm, predict a brand-new
     calmodulin–peptide complex via Boltz-2 using the wildtype PDB as a
     structural template to anchor the binding geometry.
  4. Return a clean, complete PDB path ready for fix_pdb_protonation()
     and run_prppi() in logic.py.

Dependencies
------------
  pip install pdbfixer openmm boltz[cuda]   # GPU install
  pip install pdbfixer openmm boltz          # CPU-only install

The boltz CLI must be available in the same Python environment.
Model weights are downloaded automatically on first run (~1–2 GB).
"""

import os
import re
import subprocess
import shutil
import tempfile
import yaml
from pathlib import Path
from typing import Optional

from Bio import PDB, SeqIO
from Bio.PDB import PDBParser, PDBIO, Select


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — PDB INSPECTION
# Detects what is actually wrong with the file before deciding how to fix it.
# ═══════════════════════════════════════════════════════════════════════════════

def inspect_pdb(pdb_path: str) -> dict:
    """
    Parse the PDB and return a summary of structural completeness.

    Returns a dict with keys:
      has_missing_residues  (bool) — entire residues absent from ATOM records
                                     but listed in SEQRES / REMARK 465
      has_missing_sidechains (bool) — residues present but lacking CB/CG atoms
      missing_residue_details (list of str) — human-readable descriptions
      incomplete_sidechain_residues (list of str)
      chains (list of str) — chain IDs found
    """
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("target", pdb_path)

    # ── Detect missing residues from REMARK 465 ────────────────────────────
    # REMARK 465 lists residues present in SEQRES but absent from coordinates.
    missing_residue_details = []
    with open(pdb_path) as f:
        for line in f:
            if line.startswith("REMARK 465") and len(line) > 20:
                # Standard format: REMARK 465   MET A    1
                parts = line[10:].split()
                if len(parts) >= 3:
                    missing_residue_details.append(
                        f"{parts[0]} {parts[1]} {parts[2]}"
                    )

    # ── Detect incomplete side chains in present residues ─────────────────
    # A residue is flagged if it has a CA but is missing CB (all non-Gly)
    # or is missing common side chain atoms expected for that residue.
    SIDECHAIN_CHECK = {
        # residue_name: ALL expected side-chain heavy atoms (non-backbone)
        # Backbone atoms (N, CA, C, O) are excluded — only side-chain atoms listed.
        # Source: standard PDB/wwPDB atom nomenclature for each amino acid.
        "ALA": ["CB"],
        "VAL": ["CB", "CG1", "CG2"],
        "LEU": ["CB", "CG", "CD1", "CD2"],
        "ILE": ["CB", "CG1", "CG2", "CD1"],
        "PRO": ["CB", "CG", "CD"],
        "PHE": ["CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ"],
        "TRP": ["CB", "CG", "CD1", "CD2", "NE1", "CE2", "CE3", "CZ2", "CZ3", "CH2"],
        "MET": ["CB", "CG", "SD", "CE"],
        "SER": ["CB", "OG"],
        "THR": ["CB", "OG1", "CG2"],
        "CYS": ["CB", "SG"],
        "TYR": ["CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "OH"],
        "HIS": ["CB", "CG", "ND1", "CD2", "CE1", "NE2"],
        "HIE": ["CB", "CG", "ND1", "CD2", "CE1", "NE2"],  # HIS epsilon-tautomer
        "HID": ["CB", "CG", "ND1", "CD2", "CE1", "NE2"],  # HIS delta-tautomer
        "HIP": ["CB", "CG", "ND1", "CD2", "CE1", "NE2"],  # HIS doubly protonated
        "ASP": ["CB", "CG", "OD1", "OD2"],
        "GLU": ["CB", "CG", "CD", "OE1", "OE2"],
        "ASN": ["CB", "CG", "OD1", "ND2"],
        "GLN": ["CB", "CG", "CD", "OE1", "NE2"],
        "LYS": ["CB", "CG", "CD", "CE", "NZ"],
        "ARG": ["CB", "CG", "CD", "NE", "CZ", "NH1", "NH2"],
        # GLY has no side chain — skipped in the loop above
        # SEC (selenocysteine) and PYL (pyrrolysine) are rare; omitted
    }

    incomplete_sidechain_residues = []
    chains_found = []

    for model in structure:
        for chain in model:
            cid = chain.get_id()
            if cid not in chains_found:
                chains_found.append(cid)
            for residue in chain:
                resname = residue.get_resname().strip()
                resid   = residue.get_id()[1]
                if resname == "GLY":
                    continue  # glycine has no CB by design
                atom_names = {atom.get_name() for atom in residue}
                required   = SIDECHAIN_CHECK.get(resname, [])
                missing    = [a for a in required if a not in atom_names]
                if missing:
                    incomplete_sidechain_residues.append(
                        f"{resname} {cid}{resid} (missing: {', '.join(missing)})"
                    )

    return {
        "has_missing_residues":       len(missing_residue_details) > 0,
        "has_missing_sidechains":     len(incomplete_sidechain_residues) > 0,
        "missing_residue_details":    missing_residue_details,
        "incomplete_sidechain_residues": incomplete_sidechain_residues,
        "chains":                     chains_found,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — PDBFIXER REPAIR (side chains only)
# Used when residues are all present but some lack side-chain atoms.
# Fast: runs in seconds, no GPU needed.
# ═══════════════════════════════════════════════════════════════════════════════

def repair_sidechains_pdbfixer(pdb_path: str, output_path: Optional[str] = None) -> str:
    """
    Use PDBFixer + OpenMM to rebuild missing side-chain heavy atoms.

    Parameters
    ----------
    pdb_path    : path to the incomplete PDB
    output_path : where to write the repaired PDB
                  (defaults to <stem>_sidechain_fixed.pdb next to input)

    Returns
    -------
    Path to the repaired PDB file.
    """
    try:
        from pdbfixer import PDBFixer
        from openmm.app import PDBFile
    except ImportError:
        raise ImportError(
            "PDBFixer is not installed.\n"
            "Run:  pip install pdbfixer openmm"
        )

    if output_path is None:
        stem        = Path(pdb_path).stem
        parent      = Path(pdb_path).parent
        output_path = str(parent / f"{stem}_sidechain_fixed.pdb")

    fixer = PDBFixer(filename=pdb_path)

    # Tell PDBFixer not to add missing residues — only fix atoms within
    # residues that are already present.
    fixer.findMissingResidues()
    fixer.missingResidues = {}          # ← clear: we only want side chains

    fixer.findMissingAtoms()
    fixer.addMissingAtoms()             # adds heavy atoms only (no H)

    with open(output_path, "w") as f:
        PDBFile.writeFile(fixer.topology, fixer.positions, f, keepIds=True)

    print(f"[logic5] Side-chain repair complete → {output_path}")
    return output_path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — SEQUENCE EXTRACTION
# Reads the actual sequence from ATOM records for each chain.
# Used to build the Boltz-2 YAML input.
# ═══════════════════════════════════════════════════════════════════════════════

# Standard 3-letter → 1-letter amino acid mapping
_AA3TO1 = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "HIE": "H",
    "HID": "H", "HIP": "H", "ILE": "I", "LEU": "L", "LYS": "K",
    "MET": "M", "PHE": "F", "PRO": "P", "SER": "S", "THR": "T",
    "TRP": "W", "TYR": "Y", "VAL": "V", "SEC": "U", "PYL": "O",
}

def extract_sequence_from_pdb(pdb_path: str, chain_id: str) -> str:
    """
    Extract the amino acid sequence from ATOM records for a given chain.
    Uses only residues with complete backbone (CA atom present).

    Returns a one-letter-code string.
    """
    parser  = PDBParser(QUIET=True)
    struct  = parser.get_structure("s", pdb_path)
    seq     = []
    seen    = set()

    for model in struct:
        if chain_id not in [c.get_id() for c in model]:
            continue
        chain = model[chain_id]
        for residue in chain:
            # Skip HETATM / water
            het, resseq, _ = residue.get_id()
            if het.strip():
                continue
            resname = residue.get_resname().strip()
            if resseq in seen:
                continue
            seen.add(resseq)
            aa = _AA3TO1.get(resname)
            if aa:
                seq.append(aa)

    return "".join(seq)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4 — BOLTZ-2 YAML BUILDER
# Constructs the input YAML that Boltz-2's CLI expects.
# Supports optional template conditioning (anchors to wildtype geometry).
# ═══════════════════════════════════════════════════════════════════════════════

def _build_boltz_yaml(
    cam_sequence:    str,
    peptide_sequence: str,
    cam_chain_id:    str,
    peptide_chain_id: str,
    template_pdb:    Optional[str] = None,
    yaml_path:       Optional[str] = None,
) -> str:
    """
    Write a Boltz-2 compatible YAML input file.

    template_pdb: if provided, tells Boltz-2 to use this structure as a
                  template — critical for mutant predictions so the model
                  anchors to the known binding geometry rather than
                  predicting a completely novel conformation.

    Returns the path to the written YAML file.
    """
    if yaml_path is None:
        yaml_path = tempfile.mktemp(suffix=".yaml")

    doc = {
        "version": 1,
        "sequences": [
            {
                "protein": {
                    "id": cam_chain_id,
                    "sequence": cam_sequence,
                }
            },
            {
                "protein": {
                    "id": peptide_chain_id,
                    "sequence": peptide_sequence,
                }
            },
        ]
    }

    # ── Template conditioning ──────────────────────────────────────────────
    # When predicting mutants, we pass the wildtype complex as a template.
    # Boltz-2's multi-chain template feature anchors the predicted complex
    # to the known experimental geometry, making mutant-vs-wildtype
    # comparisons meaningful for OSPREY.
    if template_pdb:
        doc["templates"] = [
            {
                "pdb": os.path.abspath(template_pdb),
                "chain_id": cam_chain_id,
            },
            {
                "pdb": os.path.abspath(template_pdb),
                "chain_id": peptide_chain_id,
            },
        ]

    with open(yaml_path, "w") as f:
        yaml.dump(doc, f, default_flow_style=False, sort_keys=False)

    return yaml_path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5 — BOLTZ-2 RUNNER
# Calls the boltz CLI, waits for completion, and extracts the output PDB.
# ═══════════════════════════════════════════════════════════════════════════════

def _run_boltz(yaml_path: str, output_dir: str, use_msa_server: bool = True) -> str:
    """
    Run Boltz-2 via its CLI and return the path to the top-ranked PDB.

    Parameters
    ----------
    yaml_path      : path to the input YAML built by _build_boltz_yaml()
    output_dir     : where Boltz-2 writes its results
    use_msa_server : use ColabFold's public MSA server (requires internet).
                     Set False if you have local MSAs or are air-gapped.

    Returns
    -------
    Path to the best-ranked output PDB (ranked_0.pdb).
    """
    os.makedirs(output_dir, exist_ok=True)

    cmd = [
        "boltz", "predict", yaml_path,
        "--out_dir", output_dir,
        "--output_format", "pdb",
    ]
    if use_msa_server:
        cmd.append("--use_msa_server")

    print(f"[logic5] Running Boltz-2: {' '.join(cmd)}")

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        raise RuntimeError(
            f"Boltz-2 failed (exit {result.returncode}):\n"
            f"STDOUT: {result.stdout}\n"
            f"STDERR: {result.stderr}"
        )

    # ── Find the output PDB ────────────────────────────────────────────────
    # Boltz-2 writes to: <out_dir>/predictions/<stem>/ranked_0.pdb
    yaml_stem   = Path(yaml_path).stem
    ranked_pdbs = list(Path(output_dir).rglob("ranked_0.pdb"))

    if not ranked_pdbs:
        # Fall back: find any .pdb in the predictions folder
        ranked_pdbs = list(Path(output_dir).rglob("*.pdb"))

    if not ranked_pdbs:
        raise FileNotFoundError(
            f"Boltz-2 ran but no output PDB found under {output_dir}.\n"
            f"STDOUT: {result.stdout}"
        )

    best_pdb = str(ranked_pdbs[0])
    print(f"[logic5] Boltz-2 output → {best_pdb}")
    return best_pdb


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6 — BOLTZ-2 REPAIR (missing residues / loops)
# Re-predicts the full complex using the existing PDB as a template.
# ═══════════════════════════════════════════════════════════════════════════════

def repair_missing_residues_boltz(
    pdb_path:        str,
    cam_chain_id:    str,
    peptide_chain_id: str,
    output_path:     Optional[str] = None,
    use_msa_server:  bool = True,
) -> str:
    """
    Use Boltz-2 to repair a PDB that has entirely missing residues/loops.

    The existing PDB is used as a structural template so Boltz-2 preserves
    the known binding geometry while filling in the missing regions.

    Parameters
    ----------
    pdb_path         : path to the incomplete PDB
    cam_chain_id     : chain letter for calmodulin (from identify_calmodulin_chain)
    peptide_chain_id : chain letter for the peptide
    output_path      : where to copy the final repaired PDB
    use_msa_server   : whether to use ColabFold's public MSA server

    Returns
    -------
    Path to the repaired PDB.
    """
    stem   = Path(pdb_path).stem
    parent = Path(pdb_path).parent

    if output_path is None:
        output_path = str(parent / f"{stem}_residue_repaired.pdb")

    # Extract sequences from whatever atoms ARE present
    cam_seq     = extract_sequence_from_pdb(pdb_path, cam_chain_id)
    peptide_seq = extract_sequence_from_pdb(pdb_path, peptide_chain_id)

    if not cam_seq:
        raise ValueError(
            f"Could not extract sequence for CaM chain '{cam_chain_id}' "
            f"from {pdb_path}. Check chain ID."
        )
    if not peptide_seq:
        raise ValueError(
            f"Could not extract sequence for peptide chain '{peptide_chain_id}' "
            f"from {pdb_path}. Check chain ID."
        )

    print(f"[logic5] CaM sequence    ({len(cam_seq)} aa): {cam_seq[:30]}...")
    print(f"[logic5] Peptide sequence ({len(peptide_seq)} aa): {peptide_seq}")

    # Build YAML — pass existing PDB as template
    boltz_dir  = str(parent / f"{stem}_boltz_repair")
    yaml_path  = str(parent / f"{stem}_repair_input.yaml")

    _build_boltz_yaml(
        cam_sequence     = cam_seq,
        peptide_sequence = peptide_seq,
        cam_chain_id     = cam_chain_id,
        peptide_chain_id = peptide_chain_id,
        template_pdb     = pdb_path,       # ← use self as template
        yaml_path        = yaml_path,
    )

    best_pdb = _run_boltz(yaml_path, boltz_dir, use_msa_server=use_msa_server)

    shutil.copy(best_pdb, output_path)
    print(f"[logic5] Residue repair complete → {output_path}")
    return output_path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 7 — MUTANT STRUCTURE PREDICTION
# Called when the algorithm generates a new peptide or CaM sequence to screen.
# ═══════════════════════════════════════════════════════════════════════════════

def predict_mutant_complex(
    wildtype_pdb_path: str,
    cam_chain_id:      str,
    peptide_chain_id:  str,
    mutant_cam_sequence:     Optional[str] = None,
    mutant_peptide_sequence: Optional[str] = None,
    output_path:       Optional[str] = None,
    use_msa_server:    bool = True,
) -> str:
    """
    Predict the structure of a mutant calmodulin–peptide complex.

    Provide either mutant_cam_sequence or mutant_peptide_sequence (or both).
    Whichever sequence is None will be taken from the wildtype PDB.
    The wildtype PDB is always used as a structural template to anchor
    the prediction to the known binding geometry.

    Parameters
    ----------
    wildtype_pdb_path        : the original (repaired) wildtype complex PDB
    cam_chain_id             : chain letter for calmodulin
    peptide_chain_id         : chain letter for the peptide
    mutant_cam_sequence      : mutant CaM sequence (1-letter codes), or None
    mutant_peptide_sequence  : mutant peptide sequence (1-letter codes), or None
    output_path              : where to save the predicted mutant PDB
    use_msa_server           : whether to use ColabFold's public MSA server

    Returns
    -------
    Path to the predicted mutant complex PDB.
    """
    if mutant_cam_sequence is None and mutant_peptide_sequence is None:
        raise ValueError(
            "At least one of mutant_cam_sequence or mutant_peptide_sequence "
            "must be provided."
        )

    # Fill in wildtype sequences for whichever chain was not mutated
    wt_cam_seq     = extract_sequence_from_pdb(wildtype_pdb_path, cam_chain_id)
    wt_peptide_seq = extract_sequence_from_pdb(wildtype_pdb_path, peptide_chain_id)

    cam_seq     = mutant_cam_sequence     if mutant_cam_sequence     else wt_cam_seq
    peptide_seq = mutant_peptide_sequence if mutant_peptide_sequence else wt_peptide_seq

    # Build a unique name for this mutant based on what changed
    if mutant_peptide_sequence and not mutant_cam_sequence:
        label = f"mutpeptide_{peptide_seq[:10]}"
    elif mutant_cam_sequence and not mutant_peptide_sequence:
        label = f"mutcam_{cam_seq[:10]}"
    else:
        label = f"mutboth_{cam_seq[:6]}_{peptide_seq[:6]}"

    stem   = Path(wildtype_pdb_path).stem
    parent = Path(wildtype_pdb_path).parent

    if output_path is None:
        output_path = str(parent / f"{stem}_{label}_predicted.pdb")

    # Build Boltz-2 YAML with wildtype PDB as template
    boltz_dir = str(parent / f"{stem}_{label}_boltz")
    yaml_path = str(parent / f"{stem}_{label}_input.yaml")

    _build_boltz_yaml(
        cam_sequence     = cam_seq,
        peptide_sequence = peptide_seq,
        cam_chain_id     = cam_chain_id,
        peptide_chain_id = peptide_chain_id,
        template_pdb     = wildtype_pdb_path,   # ← anchor to WT geometry
        yaml_path        = yaml_path,
    )

    best_pdb = _run_boltz(yaml_path, boltz_dir, use_msa_server=use_msa_server)

    shutil.copy(best_pdb, output_path)
    print(f"[logic5] Mutant prediction complete → {output_path}")
    return output_path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 8 — MASTER ENTRY POINT
# This is what gui.py and the rest of the pipeline should call.
# It decides the repair strategy automatically and returns a complete PDB.
# ═══════════════════════════════════════════════════════════════════════════════

def prepare_pdb(
    pdb_path:        str,
    cam_chain_id:    str,
    peptide_chain_id: str,
    use_msa_server:  bool = True,
) -> tuple[str, str]:
    """
    Inspect the PDB and repair it using the appropriate strategy.

    This is the main function called before run_prppi() in the pipeline.
    It detects what is wrong and routes to PDBFixer or Boltz-2 accordingly.

    Parameters
    ----------
    pdb_path         : path to the raw input PDB
    cam_chain_id     : calmodulin chain (from identify_calmodulin_chain)
    peptide_chain_id : peptide chain
    use_msa_server   : passed through to Boltz-2 if needed

    Returns
    -------
    (repaired_pdb_path, strategy_used)
      strategy_used is one of: "none_needed", "sidechain_only", "boltz_repair"
    """
    print(f"[logic5] Inspecting: {pdb_path}")
    report = inspect_pdb(pdb_path)

    print(f"[logic5] Missing residues:    {report['has_missing_residues']}")
    print(f"[logic5] Missing side chains: {report['has_missing_sidechains']}")

    if report["has_missing_residues"]:
        # ── Boltz-2 residue repair — TEMPORARILY DISABLED ─────────────────
        # Missing residues have been detected and logged above, but we are
        # not yet automatically rebuilding them. The plan is to use Boltz-2
        # with template conditioning once we decide on the right strategy.
        # Re-enable by uncommenting the block below and removing the
        # fall-through to the side-chain check.
        #
        # print("[logic5] Strategy: Boltz-2 residue repair")
        # repaired = repair_missing_residues_boltz(
        #     pdb_path         = pdb_path,
        #     cam_chain_id     = cam_chain_id,
        #     peptide_chain_id = peptide_chain_id,
        #     use_msa_server   = use_msa_server,
        # )
        # return repaired, "boltz_repair"
        #
        # For now: log a warning and fall through to the side-chain check.
        # The caller (gui.py) will display the missing-residue warning to
        # the user but will not block the pipeline.
        print(
            f"[logic5] WARNING: {len(report['missing_residue_details'])} missing "
            f"residue(s) detected but residue remodelling is currently disabled. "
            f"Proceeding with side-chain repair only if needed."
        )

    if report["has_missing_sidechains"]:
        # PDBFixer — fast, in-process
        print("[logic5] Strategy: PDBFixer side-chain repair")
        repaired = repair_sidechains_pdbfixer(pdb_path)
        return repaired, "sidechain_only"

    else:
        # Covers both a fully complete PDB and the case where only missing
        # residues were found (remodelling disabled — no action taken).
        if report["has_missing_residues"]:
            print("[logic5] Strategy: Missing residues noted — no repair applied (disabled)")
            return pdb_path, "missing_residues_skipped"
        print("[logic5] Strategy: No repair needed — PDB is complete")
        return pdb_path, "none_needed"


def get_inspection_report(pdb_path: str) -> dict:
    """
    Convenience wrapper: returns the inspection dict for display in the GUI.
    Called in Step 1 of gui.py after the PDB is uploaded.
    """
    return inspect_pdb(pdb_path)
