"""
logic6.py  –  NAMD Molecular Dynamics configuration generator
Davis Lab Software Team, 2026

This module generates NAMD-compatible config files and helper scripts
from a user-uploaded PDB. It does NOT run NAMD itself (that would take
hours); instead it packages everything the user needs to launch NAMD on
their own machine and returns a ready-to-run folder.
"""

import os
import zipfile
import textwrap


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_namd_package(
    pdb_path: str,
    output_dir: str,
    sim_steps: int = 50000,
    temperature: float = 310.0,
    timestep_fs: float = 2.0,
    nonbonded_cutoff: float = 12.0,
    gpu_enabled: bool = True,
    use_implicit_solvent: bool = True,
    protein_chain: str = "A",
    ligand_chain: str = "B",
) -> dict:
    """
    Generate a ready-to-run NAMD molecular dynamics package for a PDB file.

    Returns a dict with keys:
        config_path   – path to the .namd config file
        tcl_path      – path to the VMD preparation .tcl script
        readme_path   – path to plain-English README
        zip_path      – path to the .zip archive containing everything
        summary       – human-readable summary string
    """
    pdb_path   = os.path.abspath(pdb_path)
    pdb_name   = os.path.splitext(os.path.basename(pdb_path))[0]
    namd_dir   = os.path.join(output_dir, f"{pdb_name}_namd_package")
    os.makedirs(namd_dir, exist_ok=True)

    # ---- 1. NAMD config file -----------------------------------------------
    gpu_block = textwrap.dedent(f"""\
        # GPU acceleration (CUDA)
        CUDASOAintegrate        on
    """) if gpu_enabled else "# GPU disabled – using CPU only\n"

    solvent_block = textwrap.dedent(f"""\
        # Implicit solvent (Generalized Born) — no water box needed
        GBIS                    on
        solventDielectric       78.5
        ionConcentration        0.15
    """) if use_implicit_solvent else textwrap.dedent(f"""\
        # Explicit solvent (PME) — you must first solvate/ionize via VMD
        PME                     yes
        PMEGridSpacing          1.0
        wrapAll                 on
        wrapWater               on
    """)

    config_content = textwrap.dedent(f"""\
        # =====================================================================
        # NAMD Configuration — generated by Davis Lab CaM-RyR2 Redesign Portal
        # Structure : {pdb_name}
        # Chains    : protein={protein_chain}, ligand/peptide={ligand_chain}
        # =====================================================================

        # --- Input files ---
        structure           {pdb_name}.psf
        coordinates         {pdb_name}.pdb
        parameters          par_all36_prot.prm
        parameters          par_all36_cgenff.prm
        paratypecharmm      on

        # --- Output ---
        outputName          {pdb_name}_md
        binaryOutput        no
        dcdFile             {pdb_name}_md.dcd
        dcdFreq             1000
        restartFreq         5000
        outputEnergies      500
        outputPressure      500

        # --- Simulation settings ---
        temperature         {temperature}
        reassignFreq        500
        reassignTemp        {temperature}
        timestep            {timestep_fs}
        rigidBonds          all
        nonbondedFreq       1
        fullElectFrequency  2

        # --- Non-bonded cutoff ---
        cutoff              {nonbonded_cutoff}
        switching           on
        switchdist          {nonbonded_cutoff - 2.0}
        pairlistdist        {nonbonded_cutoff + 1.5}

        {solvent_block}
        {gpu_block}
        # --- Minimization then dynamics ---
        minimize            2000
        reinitvels          {temperature}

        run                 {sim_steps}
    """)

    config_path = os.path.join(namd_dir, f"{pdb_name}.namd")
    with open(config_path, "w", encoding="utf-8") as fh:
        fh.write(config_content)

    # ---- 2. Python PSF generation script (replaces VMD/psfgen TCL) ----------
    # VMD crashes on Windows 11 without an NVIDIA driver due to OSPRay/OptiX.
    # This standalone Python script uses parmed to generate the .psf topology
    # without requiring VMD at all. The user just runs: python generate_psf.py
    psf_script = textwrap.dedent(f'''\
        """
        generate_psf.py — Davis Lab CaM-RyR2 Portal
        ============================================
        Generates the .psf topology file needed by NAMD — no VMD required.

        Requirements:
            pip install parmed

        Usage:
            python generate_psf.py

        Place this script in the same folder as:
            {pdb_name}.pdb
            top_all36_prot.rtf
            par_all36_prot.prm
        """

        import os, sys, warnings

        try:
            import parmed as pmd
            from parmed.charmm import CharmmParameterSet
        except ImportError:
            print("ERROR: parmed not installed. Run:  pip install parmed")
            sys.exit(1)

        PDB_FILE   = "{pdb_name}.pdb"
        RTF_FILE   = "top_all36_prot.rtf"
        PRM_FILE   = "par_all36_prot.prm"
        RTF_CG     = "top_all36_cgenff.rtf"
        PRM_CG     = "par_all36_cgenff.prm"
        OUT_PSF    = "{pdb_name}.psf"
        OUT_PDB    = "{pdb_name}_prep.pdb"

        for f in [PDB_FILE, RTF_FILE, PRM_FILE]:
            if not os.path.isfile(f):
                print(f"ERROR: Missing {{f}} — make sure all files are in this folder.")
                sys.exit(1)

        ff_files = [RTF_FILE, PRM_FILE]
        for f in [RTF_CG, PRM_CG]:
            if os.path.isfile(f):
                ff_files.append(f)

        print("Loading CHARMM36 force field...")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            params = CharmmParameterSet(*ff_files)

        print(f"Loading {{PDB_FILE}}...")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            struct = pmd.load_file(PDB_FILE)

        HIS_MAP = {{"HIE": "HSE", "HID": "HSD", "HIP": "HSP", "HIS": "HSD"}}
        for res in struct.residues:
            if res.name in HIS_MAP:
                res.name = HIS_MAP[res.name]

        print("Applying parameters...")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            try:
                struct.load_parameters(params, copy=True)
            except Exception as e:
                print(f"Warning: {{e}} — continuing.")

        struct.save(OUT_PSF, overwrite=True)
        struct.save(OUT_PDB, overwrite=True)
        print(f"\\nSUCCESS — {{OUT_PSF}} and {{OUT_PDB}} written.")
        print(f"Next: update {pdb_name}.namd to use coordinates {{OUT_PDB}}")
        print(f"Then: namd2.exe +p4 {pdb_name}.namd > {pdb_name}_md.log")
    ''')

    tcl_path = os.path.join(namd_dir, "generate_psf.py")
    with open(tcl_path, "w", encoding="utf-8") as fh:
        fh.write(psf_script)

    # ---- 3b. Python analysis script (replaces VMD analysis TCL) ------------
    analysis_py = textwrap.dedent(f'''\
        """
        analyze_distance.py — Davis Lab CaM-RyR2 Portal
        ================================================
        Computes N-domain / C-domain distance from NAMD trajectory.
        No VMD required. Replicates Fig 2B from the Davis Lab manuscript.

        Requirements:
            pip install MDAnalysis

        Usage (after NAMD finishes):
            python analyze_distance.py
        """

        import os, sys
        try:
            import MDAnalysis as mda
            import numpy as np
        except ImportError:
            print("ERROR: Run:  pip install MDAnalysis")
            sys.exit(1)

        PSF_FILE = "{pdb_name}.psf"
        DCD_FILE = "{pdb_name}_md.dcd"
        OUT_FILE = "domain_distance.dat"

        for f in [PSF_FILE, DCD_FILE]:
            if not os.path.isfile(f):
                print(f"ERROR: Cannot find {{f}} — run NAMD first.")
                sys.exit(1)

        print(f"Loading trajectory...")
        u = mda.Universe(PSF_FILE, DCD_FILE)
        print(f"  Frames: {{len(u.trajectory)}}  |  Atoms: {{len(u.atoms)}}")

        sel_n = u.select_atoms("resid 40 and name CA")
        sel_c = u.select_atoms("resid 113 and name CA")
        if not sel_n or not sel_c:
            sel_n = u.select_atoms("chainID {protein_chain} and resid 40 and name CA")
            sel_c = u.select_atoms("chainID {protein_chain} and resid 113 and name CA")

        frames, distances = [], []
        for ts in u.trajectory:
            diff = sel_n.positions[0] - sel_c.positions[0]
            distances.append(float(np.linalg.norm(diff) / 10.0))
            frames.append(ts.frame)

        with open(OUT_FILE, "w") as f:
            f.write("# Frame   Distance_nm\\n")
            for fr, d in zip(frames, distances):
                f.write(f"{{fr}}   {{d:.4f}}\\n")

        arr = np.array(distances)
        print(f"\\nSaved {{OUT_FILE}}")
        print(f"  Mean: {{arr.mean():.3f}} nm  |  Min: {{arr.min():.3f}}  |  Max: {{arr.max():.3f}}")
        print("  <1.0 nm = annealed (good) | >1.5 nm = unlocked (RCaM1-like)")
        print(f"\\nUpload {{OUT_FILE}} to the portal Results tab.")
    ''')

    analysis_path = os.path.join(namd_dir, "analyze_distance.py")
    with open(analysis_path, "w", encoding="utf-8") as fh:
        fh.write(analysis_py)

    # ---- 4. Plain-English README -------------------------------------------
    steps_solvent = (
        "implicit solvent (Generalized Born) — no water box required"
        if use_implicit_solvent
        else "explicit solvent (PME) — you must solvate and ionize first in VMD"
    )
    readme_content = textwrap.dedent(f"""\
        Davis Lab CaM-RyR2 Portal — NAMD Package for {pdb_name}
        =========================================================

        Generated settings
        ------------------
        PDB             : {pdb_name}
        Temperature     : {temperature} K  (~{temperature - 273:.0f} °C)
        Timestep        : {timestep_fs} fs
        Simulation steps: {sim_steps:,}  ({sim_steps * timestep_fs / 1e6:.2f} ns)
        Cutoff          : {nonbonded_cutoff} Å
        Solvent model   : {steps_solvent}
        GPU             : {"Enabled (CUDA)" if gpu_enabled else "Disabled"}

        Files in this package
        ---------------------
        {pdb_name}.namd           — Main NAMD configuration (edit parameters here)
        {pdb_name}_prep.tcl       — VMD/psfgen script to generate .psf topology
        {pdb_name}_analysis.tcl   — Post-simulation VMD analysis (N/C domain distance)
        README.txt                — This file

        Quick-start steps
        -----------------
        1. Install NAMD (https://www.ks.uiuc.edu/Research/namd/) — Win64 multicore build.

        2. Install parmed (open Command Prompt and run):
               pip install parmed

        3. Download CHARMM36 force-field files from
           http://mackerell.umaryland.edu/charmm_ff.shtml
           and place top_all36_prot.rtf / par_all36_prot.prm in this folder.

        4. Copy your PDB file ({pdb_name}.pdb) into this folder.

        5. Generate the .psf topology (no VMD needed):
               python generate_psf.py
           This creates {pdb_name}.psf and {pdb_name}_prep.pdb.

        6. Update {pdb_name}.namd — change "coordinates {pdb_name}.pdb"
           to "coordinates {pdb_name}_prep.pdb"

        7. Launch NAMD:
               namd2.exe +p4 {pdb_name}.namd > {pdb_name}_md.log

        8. After simulation, run the Python analysis script:
               python analyze_distance.py
           This writes domain_distance.dat which you upload back to the portal.

        What the simulation tells you (context from Davis Lab manuscript)
        -----------------------------------------------------------------
        Track the N-domain (residue 40) to C-domain (residue 113) Cα distance
        over time. Wild-type CaM stays in the "annealed" state (low distance,
        ~0.5-1.0 nm). RCaM1 opens to an "unlocked" state (high distance,
        ~1.5-3.0 nm) and bends the RyR2 peptide. RCaM2 (the successful redesign)
        stays locked in the annealed state while improving binding affinity.

        Support
        -------
        For NAMD documentation: https://www.ks.uiuc.edu/Research/namd/
        For OSPREY pipeline questions: contact the Davis Lab.
    """)

    readme_path = os.path.join(namd_dir, "README.txt")
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(readme_content)

    # ---- 5. Windows batch launcher -----------------------------------------
    bat_content = textwrap.dedent(f"""\
        @echo off
        REM Davis Lab — NAMD launcher (Windows + CUDA)
        REM Run this after completing psfgen prep in VMD

        set NAMD=C:\\namd3\\namd3.exe
        set CONFIG={pdb_name}.namd
        set LOG={pdb_name}_md.log

        echo Starting NAMD simulation...
        %NAMD% +p8 +devices 0 %CONFIG% > %LOG%
        echo Done! Check %LOG% for results.
        pause
    """)

    bat_path = os.path.join(namd_dir, f"run_namd_{pdb_name}.bat")
    with open(bat_path, "w", encoding="utf-8") as fh:
        fh.write(bat_content)

    # ---- 6. Zip everything up ----------------------------------------------
    zip_path = os.path.join(output_dir, f"{pdb_name}_namd_package.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in os.listdir(namd_dir):
            zf.write(os.path.join(namd_dir, fname), arcname=fname)
        zf.write(pdb_path, arcname=os.path.basename(pdb_path))

    sim_ns = sim_steps * timestep_fs / 1_000_000
    summary = (
        f"Generated NAMD package for **{pdb_name}** — "
        f"{sim_ns:.2f} ns simulation at {temperature} K, "
        f"{'GPU (CUDA)' if gpu_enabled else 'CPU only'}, "
        f"{'implicit' if use_implicit_solvent else 'explicit'} solvent."
    )

    return {
        "config_path":   config_path,
        "tcl_path":      tcl_path,
        "analysis_path": analysis_path,
        "bat_path":      bat_path,
        "readme_path":   readme_path,
        "zip_path":      zip_path,
        "namd_dir":      namd_dir,
        "summary":       summary,
    }


def parse_domain_distance_dat(dat_text: str) -> list[dict]:
    """
    Parse the domain_distance.dat file produced by the VMD analysis TCL script.
    Returns a list of {frame: int, distance_nm: float} dicts.
    """
    rows = []
    for line in dat_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            try:
                rows.append({"frame": int(parts[0]), "distance_nm": float(parts[1])})
            except ValueError:
                continue
    return rows