import streamlit as st
import pandas as pd
import time

#Page Configuration
st.set_page_config(page_title="Davis Lab Redesign", layout="wide")

#UI Header
st.title("CaM-RyR2 Protein Redesign Portal")
st.markdown("""
**Status:** Unified Workflow v1.0 (Draft)  
*Meeting ISO/IEC 25010:2023 Efficiency Standards*
""")

st.sidebar.header("Pipeline Controls")
workflow_step = st.sidebar.radio("Navigate Workflow", 
    ["1. Data Input", "2. OSPREY Execution", "3. Results & Analytics"])

#Step 1: Data Input
if workflow_step == "1. Data Input":
    st.header("Step 1: Interaction Data Input")
    st.info("Upload the JSON distance file generated by prppi.")
    
    uploaded_json = st.file_uploader("Upload Interaction JSON", type=['json'])
    pdb_id = st.text_input("Enter Target PDB ID (e.g., 2RL0)", "2RL0")
    
    if uploaded_json:
        st.success(f"Successfully parsed interactions for {pdb_id}")

#Step 2: OSPREY Execution
elif workflow_step == "2. OSPREY Execution":
    st.header("Step 2: OSPREY Simulation Setup")
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Design Site")
        target_res = st.selectbox("Select Residue to Mutate", ["G649", "G654", "A156"])
        mutations = st.multiselect("Select Amino Acids", 
            ['ALA', 'VAL', 'ILE', 'LEU', 'MET', 'PHE', 'TRP', 'GLU', 'TYR', 'ASP'])
        
    with col2:
        st.subheader("Parameters")
        epsilon = st.slider("K* Precision (Epsilon)", 0.01, 1.0, 0.99)
        cores = st.number_input("CPU Cores", 1, 16, 4)

    if st.button("Generate & Run OSPREY Script"):
        with st.status("Generating OSPREY Script...", expanded=True) as status:
            st.write("Configuring Forcefield...")
            time.sleep(1)
            st.write(f"Setting flexibility for {target_res}...")
            time.sleep(1)
            status.update(label="Simulation Running!", state="running")
            st.code(f"osprey.start(2048)\nprotein.flexibility['{target_res}'].setLibraryRotamers('WILD_TYPE', {mutations})", language="python")

#Step 3: Results
elif workflow_step == "3. Results & Analytics":
    st.header("Step 3: Redesign Results")
    
    # Mock data to show off the visualization
    data = {
        'Mutation': ['WT', 'ALA', 'VAL', 'ILE', 'LEU'],
        'K* Score': [10.2, 12.5, 9.8, 14.1, 11.2],
        'Stability': ['Stable', 'Stable', 'Unstable', 'Very Stable', 'Stable']
    }
    df = pd.DataFrame(data)
    df['Delta K*'] = df['K* Score'] - 10.2

    st.subheader("Binding Affinity Ranking (ΔK*)")
    st.bar_chart(df, x="Mutation", y="Delta K*")
    
    st.subheader("Sequence Details")
    st.table(df)

#Sidebar/Footer
st.sidebar.markdown("---")
st.sidebar.write("**Software Team (Davis Lab)**")
