import os
import pandas as pd
import io

def get_tsv_files_paths(base_dir):
    """Finds all OSPREY results files in the directory tree."""
    tsv_files = []
    for root, _, files in os.walk(base_dir):
        for file in files:
            # Look for the specific result files generated by OSPREY
            if file.endswith('.tsv') and 'bbkstar_results' in file:
                tsv_files.append(os.path.join(root, file))
    return tsv_files

def extract_unique_name_fragments(tsv_file, unique_name_fragments_set):
    """Extracts the 'fragment' part of the filename (e.g., 'out')."""
    basename = os.path.basename(tsv_file)
    name_no_ext = os.path.splitext(basename)[0]
    parts = name_no_ext.split('_')
    
    # Logic: bbkstar_results_{fragment}_{residue}
    if len(parts) >= 4:
        fragment = "_".join(parts[2:-1])
        unique_name_fragments_set.add(fragment)
        return fragment
    return None

def read_file_data(tsv_file):
    """Robustly reads the TSV and returns a list of (WT_Seq, Mut_AA, Delta_K)."""
    try:
        with open(tsv_file, 'r') as f:
            lines = f.readlines()

        # OSPREY TSV format:
        #   line 0: wild-type row (data)
        #   line 1: header row
        #   line 2+: mutation rows
        if len(lines) < 3:
            return None

        header = lines[1].strip().split('\t')

        # Find columns
        try:
            seq_idx = header.index('Sequence')
        except ValueError:
            return None

        possible_cols = ['K* Lower (log10)', 'K* Score (Log10)', 'K* Score (log10)', 'K* Upper (log10)']
        score_idx = None
        for col in possible_cols:
            if col in header:
                score_idx = header.index(col)
                break
        if score_idx is None:
            return None

        # Wild-type is line 0
        wt_parts = lines[0].strip().split('\t')
        wt_score = float(wt_parts[score_idx])
        wt_full_name = wt_parts[seq_idx]  # e.g. "A111=asn"

        results = []
        # Wild-type itself (delta = 0)
        wt_aa = wt_full_name.split('=')[-1].upper()
        results.append({
            'WT_Full': wt_full_name,
            'Mutation': wt_aa,
            'Score': round(wt_score, 3),
            'Delta': 0.0
        })

        # Mutations are lines 2+
        for line in lines[2:]:
            parts = line.strip().split('\t')
            if len(parts) <= max(seq_idx, score_idx):
                continue
            mut_aa = parts[seq_idx].split('=')[-1].upper()
            try:
                score = float(parts[score_idx])
            except ValueError:
                continue
            delta = score - wt_score
            results.append({
                'WT_Full': wt_full_name,
                'Mutation': mut_aa,
                'Score': round(score, 3),
                'Delta': round(delta, 3)
            })
        return results
    except Exception as e:
        print(f"Error parsing {tsv_file}: {e}")
        return None

def analyze_results(base_dir):
    """
    THIS IS THE FUNCTION CALLED BY gui.py
    Processes all files and returns (pivot_delta, pivot_annot, summary_df, error_msg)
    pivot_delta: numeric ΔK* matrix (rows=residue sites, cols=mutations)
    pivot_annot: single-letter amino acid annotation matrix (same shape)
    """
    tsv_files_paths = get_tsv_files_paths(base_dir)
    if not tsv_files_paths:
        return None, None, None, "No TSV files found in output directory."

    unique_fragments = set()
    all_rows = []

    for path in tsv_files_paths:
        fragment = extract_unique_name_fragments(path, unique_fragments)
        data_list = read_file_data(path)
        
        if data_list and fragment:
            for item in data_list:
                item['Fragment'] = fragment
                all_rows.append(item)

    if not all_rows:
        return None, None, None, "No valid data found inside TSV files."

    # Create Master DataFrame
    master_df = pd.DataFrame(all_rows)

    # Single-letter amino acid conversion
    AA_3TO1 = {
        'ALA': 'A', 'VAL': 'V', 'ILE': 'I', 'LEU': 'L', 'MET': 'M',
        'PHE': 'F', 'TRP': 'W', 'GLU': 'E', 'TYR': 'Y', 'ASP': 'D',
        'ASN': 'N', 'GLN': 'Q', 'ARG': 'R', 'LYS': 'K', 'SER': 'S',
        'THR': 'T', 'CYS': 'C', 'HIS': 'H', 'PRO': 'P', 'GLY': 'G',
    }
    master_df['AA1'] = master_df['Mutation'].map(lambda x: AA_3TO1.get(x.upper(), x[0]))

    # Sort rows by residue number
    def residue_sort_key(s):
        digits = ''.join(filter(str.isdigit, s))
        return int(digits) if digits else 0

    # Delta pivot (numeric, for color)
    pivot_delta = master_df.pivot_table(
        index='WT_Full',
        columns='Fragment',
        values='Delta',
        aggfunc='first'
    ).sort_index(key=lambda idx: idx.map(residue_sort_key))

    # Annotation pivot (single-letter AA, for cell text)
    pivot_annot = master_df.pivot_table(
        index='WT_Full',
        columns='Fragment',
        values='AA1',
        aggfunc='first'
    ).reindex(pivot_delta.index)

    # Summary Table
    summary_df = master_df.copy()
    summary_df['Label'] = summary_df['Mutation'] + " (" + summary_df['Score'].astype(str) + ")"
    mutation_summary = summary_df.groupby('WT_Full')['Label'].apply(lambda x: ', '.join(x)).reset_index()
    mutation_summary.rename(columns={'WT_Full': 'Residue Site', 'Label': 'Mutations & Log10 Scores'}, inplace=True)

    return pivot_delta, pivot_annot, mutation_summary, None