import os
import pandas as pd
import io

def get_tsv_files_paths(base_dir):
    """Finds all OSPREY results files in the directory tree."""
    tsv_files = []
    for root, _, files in os.walk(base_dir):
        for file in files:
            # Look for the specific result files generated by OSPREY
            if file.endswith('.tsv') and 'bbkstar_results' in file:
                tsv_files.append(os.path.join(root, file))
    return tsv_files

def extract_unique_name_fragments(tsv_file, unique_name_fragments_set):
    """Extracts the 'fragment' part of the filename (e.g., 'out')."""
    basename = os.path.basename(tsv_file)
    name_no_ext = os.path.splitext(basename)[0]
    parts = name_no_ext.split('_')
    
    # Logic: bbkstar_results_{fragment}_{residue}
    if len(parts) >= 4:
        fragment = "_".join(parts[2:-1])
        unique_name_fragments_set.add(fragment)
        return fragment
    return None

def read_file_data(tsv_file):
    """Robustly reads the TSV and returns a list of (WT_Seq, Mut_AA, Delta_K)."""
    try:
        with open(tsv_file, 'r') as f:
            lines = f.readlines()
        
        # Find the header (OSPREY sometimes puts meta-data in the first few lines)
        header_idx = -1
        for i, line in enumerate(lines):
            if 'Sequence' in line and 'K*' in line:
                header_idx = i
                break
        
        if header_idx == -1: return None

        # Read the table
        csv_data = "".join(lines[header_idx:])
        df = pd.read_csv(io.StringIO(csv_data), sep='\t')
        
        # Identify the correct K* column
        possible_cols = ['K* Lower (log10)', 'K* Score (Log10)', 'K* Score (log10)']
        score_col = next((c for c in possible_cols if c in df.columns), None)
        
        if score_col is None or 'Sequence' not in df.columns: return None

        # The first row is always the reference (Wild-Type)
        wt_score = float(df.iloc[0][score_col])
        wt_full_name = df.iloc[0]['Sequence'] # e.g. "A11=glu"

        results = []
        for _, row in df.iterrows():
            # Get the amino acid name (e.g. "LEU" from "A11=LEU")
            mut_aa = str(row['Sequence']).split('=')[-1].upper()
            score = float(row[score_col])
            delta = score - wt_score
            
            results.append({
                'WT_Full': wt_full_name,
                'Mutation': mut_aa,
                'Score': round(score, 3),
                'Delta': round(delta, 3)
            })
        return results
    except Exception as e:
        print(f"Error parsing {tsv_file}: {e}")
        return None

def analyze_results(base_dir):
    """
    THIS IS THE FUNCTION CALLED BY gui.py
    Processes all files and returns (pivot_df, summary_df, error_msg)
    """
    tsv_files_paths = get_tsv_files_paths(base_dir)
    if not tsv_files_paths:
        return None, None, "No TSV files found in output directory."

    unique_fragments = set()
    all_rows = []

    for path in tsv_files_paths:
        fragment = extract_unique_name_fragments(path, unique_fragments)
        data_list = read_file_data(path)
        
        if data_list and fragment:
            for item in data_list:
                item['Fragment'] = fragment
                all_rows.append(item)

    if not all_rows:
        return None, None, "No valid data found inside TSV files."

    # Create Master DataFrame
    master_df = pd.DataFrame(all_rows)

    # DataFrame 1: The Matrix for the Bar Chart (Pivot Table)
    # This aligns different mutations (columns) against residue sites (rows)
    pivot_delta = master_df.pivot_table(
        index=['WT_Full'], 
        columns='Mutation', 
        values='Delta',
        aggfunc='first'
    ).fillna(0).sort_index()

    # DataFrame 2: The Summary Table for the UI
    # Combines mutation name and score into a readable string
    summary_df = master_df.copy()
    summary_df['Label'] = summary_df['Mutation'] + " (" + summary_df['Score'].astype(str) + ")"
    mutation_summary = summary_df.groupby(['WT_Full'])['Label'].apply(lambda x: ', '.join(x)).reset_index()
    mutation_summary.rename(columns={'WT_Full': 'Residue Site', 'Label': 'Mutations & Log10 Scores'}, inplace=True)

    return pivot_delta, mutation_summary, None